.TH Backblaze-B2 "1" "August 2019" "backblaze-b2" "User Commands"
.SH NAME
backblaze-b2 \- B2 Command Line Tool
.SH DESCRIPTION
This program provides command\-line access to the B2 service.
.PP
Usages:
.IP
backblaze-b2 authorize\-account [<accountId>] [<applicationKey>]
.br
backblaze-b2 cancel\-all\-unfinished\-large\-files <bucketName>
.br
backblaze-b2 cancel\-large\-file <fileId>
.br
backblaze-b2 clear\-account
.br
backblaze-b2 create\-bucket [\-\-bucketInfo <json>] [\-\-corsRules <json>] [\-\-lifecycleRules <json>] \e
.RS 14
.br
<bucketName> [allPublic | allPrivate]
.RE
.RS 7
.br
backblaze-b2 delete\-bucket <bucketName>
.br
backblaze-b2 delete\-file\-version [<fileName>] <fileId>
.br
backblaze-b2 download\-file\-by\-id [\-\-noProgress] <fileId> <localFileName>
.br
backblaze-b2 download\-file\-by\-name [\-\-noProgress] <bucketName> <fileName> <localFileName>
.br
backblaze-b2 get\-account\-info
.br
backblaze-b2 get\-bucket <bucketName>
.br
backblaze-b2 get\-download\-auth [\-\-prefix <fileNamePrefix>] [\-\-duration <durationInSeconds>] <bucketName>
.br
backblaze-b2 get\-file\-info <fileId>
.br
backblaze-b2 help [commandName]
.br
backblaze-b2 hide\-file <bucketName> <fileName>
.br
backblaze-b2 list\-buckets
.br
backblaze-b2 list\-file\-names <bucketName> [<startFileName>] [<maxToShow>]
.br
backblaze-b2 list\-file\-versions <bucketName> [<startFileName>] [<startFileId>] [<maxToShow>]
.br
backblaze-b2 list\-parts <largeFileId>
.br
backblaze-b2 list\-unfinished\-large\-files <bucketName>
.br
backblaze-b2 ls [\-\-long] [\-\-versions] <bucketName> [<folderName>]
.br
backblaze-b2 make\-url <fileId>
.br
backblaze-b2 sync [\-\-delete] [\-\-keepDays N] [\-\-skipNewer] [\-\-replaceNewer] \e
.RS 7
.br
[\-\-compareVersions <option>] [\-\-threads N] [\-\-noProgress] \e
.br
[\-\-excludeRegex <regex> [\-\-includeRegex <regex>]] [\-\-dryRun] \e
.br
<source> <destination>
.RE
.RS 0
.br
backblaze-b2 update\-bucket [\-\-bucketInfo <json>] [\-\-corsRules <json>] [\-\-lifecycleRules <json>] \e
.RS 7
.br
<bucketName> [allPublic | allPrivate]
.RE
.RS 0
.br
backblaze-b2 upload\-file [\-\-sha1 <sha1sum>] [\-\-contentType <contentType>] \e
.RS 7
.br
[\-\-info <key>=<value>]* [\-\-minPartSize N] \e
.br
[\-\-noProgress] [\-\-threads N] <bucketName> <localFilePath> <b2FileName>
.RE
backblaze-b2 version
.PP
For more details on one command: b2 help <command>
.SH COPYRIGHT
Copyright 2015 - 2019, Backblaze, Inc. <support@backblaze.com>
.SH AUTHOR
This manual page was generated by help2man 1.47.4 and amended by Ondrej Koblizek <koblizeko@gmail.com>.
